version: "3.1"

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgresdb
    networks:
      - postgres-compose-network
volumes:
  postgresql-volume:
    external: true
networks:
  postgres-compose-network:
    driver: bridge